# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.pilling.rpc.protos.client_control_pb2 as client__control__pb2


class ClientControlStub(object):
  """Client control service 
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDelayedPaymentTargets = channel.unary_unary(
        '/ClientControl/GetDelayedPaymentTargets',
        request_serializer=client__control__pb2.GetDelayedPaymentTargetsRequest.SerializeToString,
        response_deserializer=client__control__pb2.GetDelayedPaymentTargetsReply.FromString,
        )
    self.GetDelayedPayments = channel.unary_unary(
        '/ClientControl/GetDelayedPayments',
        request_serializer=client__control__pb2.GetDelayedPaymentsRequest.SerializeToString,
        response_deserializer=client__control__pb2.GetDelayedPaymentsReply.FromString,
        )
    self.SetDelayedPayment = channel.unary_unary(
        '/ClientControl/SetDelayedPayment',
        request_serializer=client__control__pb2.SetDelayedPaymentRequest.SerializeToString,
        response_deserializer=client__control__pb2.SetDelayedPaymentReply.FromString,
        )
    self.GetVoluntaryBlockTargets = channel.unary_unary(
        '/ClientControl/GetVoluntaryBlockTargets',
        request_serializer=client__control__pb2.GetVoluntaryBlockTargetsRequest.SerializeToString,
        response_deserializer=client__control__pb2.GetVoluntaryBlockTargetsReply.FromString,
        )
    self.GetVoluntaryBlocks = channel.unary_unary(
        '/ClientControl/GetVoluntaryBlocks',
        request_serializer=client__control__pb2.GetVoluntaryBlocksRequest.SerializeToString,
        response_deserializer=client__control__pb2.GetVoluntaryBlocksReply.FromString,
        )
    self.SetVoluntaryBlock = channel.unary_unary(
        '/ClientControl/SetVoluntaryBlock',
        request_serializer=client__control__pb2.SetVoluntaryBlockRequest.SerializeToString,
        response_deserializer=client__control__pb2.SetVoluntaryBlockReply.FromString,
        )


class ClientControlServicer(object):
  """Client control service 
  """

  def GetDelayedPaymentTargets(self, request, context):
    """Get delayed payment available targets 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDelayedPayments(self, request, context):
    """Get delayed payments 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDelayedPayment(self, request, context):
    """Set delayed payment 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVoluntaryBlockTargets(self, request, context):
    """Get voluntary block 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVoluntaryBlocks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetVoluntaryBlock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClientControlServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDelayedPaymentTargets': grpc.unary_unary_rpc_method_handler(
          servicer.GetDelayedPaymentTargets,
          request_deserializer=client__control__pb2.GetDelayedPaymentTargetsRequest.FromString,
          response_serializer=client__control__pb2.GetDelayedPaymentTargetsReply.SerializeToString,
      ),
      'GetDelayedPayments': grpc.unary_unary_rpc_method_handler(
          servicer.GetDelayedPayments,
          request_deserializer=client__control__pb2.GetDelayedPaymentsRequest.FromString,
          response_serializer=client__control__pb2.GetDelayedPaymentsReply.SerializeToString,
      ),
      'SetDelayedPayment': grpc.unary_unary_rpc_method_handler(
          servicer.SetDelayedPayment,
          request_deserializer=client__control__pb2.SetDelayedPaymentRequest.FromString,
          response_serializer=client__control__pb2.SetDelayedPaymentReply.SerializeToString,
      ),
      'GetVoluntaryBlockTargets': grpc.unary_unary_rpc_method_handler(
          servicer.GetVoluntaryBlockTargets,
          request_deserializer=client__control__pb2.GetVoluntaryBlockTargetsRequest.FromString,
          response_serializer=client__control__pb2.GetVoluntaryBlockTargetsReply.SerializeToString,
      ),
      'GetVoluntaryBlocks': grpc.unary_unary_rpc_method_handler(
          servicer.GetVoluntaryBlocks,
          request_deserializer=client__control__pb2.GetVoluntaryBlocksRequest.FromString,
          response_serializer=client__control__pb2.GetVoluntaryBlocksReply.SerializeToString,
      ),
      'SetVoluntaryBlock': grpc.unary_unary_rpc_method_handler(
          servicer.SetVoluntaryBlock,
          request_deserializer=client__control__pb2.SetVoluntaryBlockRequest.FromString,
          response_serializer=client__control__pb2.SetVoluntaryBlockReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ClientControl', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
