# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.pilling.rpc.protos.expenses_pb2 as expenses__pb2


class ExpensesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetExpensesPeriods = channel.unary_unary(
        '/Expenses/GetExpensesPeriods',
        request_serializer=expenses__pb2.GetExpensesPeriodsRequest.SerializeToString,
        response_deserializer=expenses__pb2.GetExpensesPeriodsReply.FromString,
        )
    self.GetExpensesForPeriod = channel.unary_unary(
        '/Expenses/GetExpensesForPeriod',
        request_serializer=expenses__pb2.GetExpensesForPeriodRequest.SerializeToString,
        response_deserializer=expenses__pb2.GetExpensesForPeriodReply.FromString,
        )


class ExpensesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetExpensesPeriods(self, request, context):
    """Get expenses periods, order by time 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExpensesForPeriod(self, request, context):
    """Get expenses for period 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExpensesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetExpensesPeriods': grpc.unary_unary_rpc_method_handler(
          servicer.GetExpensesPeriods,
          request_deserializer=expenses__pb2.GetExpensesPeriodsRequest.FromString,
          response_serializer=expenses__pb2.GetExpensesPeriodsReply.SerializeToString,
      ),
      'GetExpensesForPeriod': grpc.unary_unary_rpc_method_handler(
          servicer.GetExpensesForPeriod,
          request_deserializer=expenses__pb2.GetExpensesForPeriodRequest.FromString,
          response_serializer=expenses__pb2.GetExpensesForPeriodReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Expenses', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
