# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: expenses.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='expenses.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65xpenses.proto\"R\n\x19GetExpensesPeriodsRequest\x12\x11\n\tclient_id\x18\x01 \x02(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x13\n\x04\x64\x65sc\x18\x03 \x01(\x08:\x05\x66\x61lse\"\\\n\x1bGetExpensesForPeriodRequest\x12\x11\n\tclient_id\x18\x01 \x02(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x02(\x05\x12\r\n\x05month\x18\x04 \x01(\x05\"@\n\x17GetExpensesPeriodsReply\x12%\n\x07periods\x18\x01 \x03(\x0b\x32\x14.ExpensesPeriodReply\"2\n\x13\x45xpensesPeriodReply\x12\x0c\n\x04year\x18\x01 \x02(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\"\xae\x01\n\x19GetExpensesForPeriodReply\x12\x0c\n\x04year\x18\x01 \x02(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x12\n\ntotal_cost\x18\x03 \x02(\x03\x12\x18\n\x10\x63onditional_cost\x18\x04 \x02(\x03\x12\x1a\n\x12unconditional_cost\x18\x05 \x02(\x03\x12*\n\tresources\x18\x06 \x02(\x0b\x32\x17.ResourcesExpensesReply\"J\n\x16ResourcesExpensesReply\x12\x17\n\x03ip4\x18\x01 \x03(\x0b\x32\n.IpTraffic\x12\x17\n\x03ip6\x18\x02 \x03(\x0b\x32\n.IpTraffic\"b\n\tIpTraffic\x12\x13\n\x0b\x61\x64\x64ress_net\x18\x01 \x02(\t\x12\x13\n\x0blocal_bytes\x18\x02 \x02(\x03\x12\x16\n\x0e\x65xternal_bytes\x18\x03 \x02(\x03\x12\x13\n\x0btotal_bytes\x18\x04 \x02(\x03\x32\xac\x01\n\x08\x45xpenses\x12L\n\x12GetExpensesPeriods\x12\x1a.GetExpensesPeriodsRequest\x1a\x18.GetExpensesPeriodsReply\"\x00\x12R\n\x14GetExpensesForPeriod\x12\x1c.GetExpensesForPeriodRequest\x1a\x1a.GetExpensesForPeriodReply\"\x00')
)




_GETEXPENSESPERIODSREQUEST = _descriptor.Descriptor(
  name='GetExpensesPeriodsRequest',
  full_name='GetExpensesPeriodsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='GetExpensesPeriodsRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login', full_name='GetExpensesPeriodsRequest.login', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='GetExpensesPeriodsRequest.desc', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=100,
)


_GETEXPENSESFORPERIODREQUEST = _descriptor.Descriptor(
  name='GetExpensesForPeriodRequest',
  full_name='GetExpensesForPeriodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='GetExpensesForPeriodRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='login', full_name='GetExpensesForPeriodRequest.login', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='GetExpensesForPeriodRequest.year', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='GetExpensesForPeriodRequest.month', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=194,
)


_GETEXPENSESPERIODSREPLY = _descriptor.Descriptor(
  name='GetExpensesPeriodsReply',
  full_name='GetExpensesPeriodsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='periods', full_name='GetExpensesPeriodsReply.periods', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=260,
)


_EXPENSESPERIODREPLY = _descriptor.Descriptor(
  name='ExpensesPeriodReply',
  full_name='ExpensesPeriodReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='ExpensesPeriodReply.year', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='ExpensesPeriodReply.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=312,
)


_GETEXPENSESFORPERIODREPLY = _descriptor.Descriptor(
  name='GetExpensesForPeriodReply',
  full_name='GetExpensesForPeriodReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='GetExpensesForPeriodReply.year', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='GetExpensesForPeriodReply.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_cost', full_name='GetExpensesForPeriodReply.total_cost', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditional_cost', full_name='GetExpensesForPeriodReply.conditional_cost', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unconditional_cost', full_name='GetExpensesForPeriodReply.unconditional_cost', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resources', full_name='GetExpensesForPeriodReply.resources', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=489,
)


_RESOURCESEXPENSESREPLY = _descriptor.Descriptor(
  name='ResourcesExpensesReply',
  full_name='ResourcesExpensesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip4', full_name='ResourcesExpensesReply.ip4', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip6', full_name='ResourcesExpensesReply.ip6', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=565,
)


_IPTRAFFIC = _descriptor.Descriptor(
  name='IpTraffic',
  full_name='IpTraffic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_net', full_name='IpTraffic.address_net', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_bytes', full_name='IpTraffic.local_bytes', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='external_bytes', full_name='IpTraffic.external_bytes', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_bytes', full_name='IpTraffic.total_bytes', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=665,
)

_GETEXPENSESPERIODSREPLY.fields_by_name['periods'].message_type = _EXPENSESPERIODREPLY
_GETEXPENSESFORPERIODREPLY.fields_by_name['resources'].message_type = _RESOURCESEXPENSESREPLY
_RESOURCESEXPENSESREPLY.fields_by_name['ip4'].message_type = _IPTRAFFIC
_RESOURCESEXPENSESREPLY.fields_by_name['ip6'].message_type = _IPTRAFFIC
DESCRIPTOR.message_types_by_name['GetExpensesPeriodsRequest'] = _GETEXPENSESPERIODSREQUEST
DESCRIPTOR.message_types_by_name['GetExpensesForPeriodRequest'] = _GETEXPENSESFORPERIODREQUEST
DESCRIPTOR.message_types_by_name['GetExpensesPeriodsReply'] = _GETEXPENSESPERIODSREPLY
DESCRIPTOR.message_types_by_name['ExpensesPeriodReply'] = _EXPENSESPERIODREPLY
DESCRIPTOR.message_types_by_name['GetExpensesForPeriodReply'] = _GETEXPENSESFORPERIODREPLY
DESCRIPTOR.message_types_by_name['ResourcesExpensesReply'] = _RESOURCESEXPENSESREPLY
DESCRIPTOR.message_types_by_name['IpTraffic'] = _IPTRAFFIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetExpensesPeriodsRequest = _reflection.GeneratedProtocolMessageType('GetExpensesPeriodsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETEXPENSESPERIODSREQUEST,
  __module__ = 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:GetExpensesPeriodsRequest)
  ))
_sym_db.RegisterMessage(GetExpensesPeriodsRequest)

GetExpensesForPeriodRequest = _reflection.GeneratedProtocolMessageType('GetExpensesForPeriodRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETEXPENSESFORPERIODREQUEST,
  __module__ = 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:GetExpensesForPeriodRequest)
  ))
_sym_db.RegisterMessage(GetExpensesForPeriodRequest)

GetExpensesPeriodsReply = _reflection.GeneratedProtocolMessageType('GetExpensesPeriodsReply', (_message.Message,), dict(
  DESCRIPTOR = _GETEXPENSESPERIODSREPLY,
  __module__ = 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:GetExpensesPeriodsReply)
  ))
_sym_db.RegisterMessage(GetExpensesPeriodsReply)

ExpensesPeriodReply = _reflection.GeneratedProtocolMessageType('ExpensesPeriodReply', (_message.Message,), dict(
  DESCRIPTOR = _EXPENSESPERIODREPLY,
  __module__ = 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:ExpensesPeriodReply)
  ))
_sym_db.RegisterMessage(ExpensesPeriodReply)

GetExpensesForPeriodReply = _reflection.GeneratedProtocolMessageType('GetExpensesForPeriodReply', (_message.Message,), dict(
  DESCRIPTOR = _GETEXPENSESFORPERIODREPLY,
  __module__ = 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:GetExpensesForPeriodReply)
  ))
_sym_db.RegisterMessage(GetExpensesForPeriodReply)

ResourcesExpensesReply = _reflection.GeneratedProtocolMessageType('ResourcesExpensesReply', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCESEXPENSESREPLY,
  __module__ = 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:ResourcesExpensesReply)
  ))
_sym_db.RegisterMessage(ResourcesExpensesReply)

IpTraffic = _reflection.GeneratedProtocolMessageType('IpTraffic', (_message.Message,), dict(
  DESCRIPTOR = _IPTRAFFIC,
  __module__ = 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:IpTraffic)
  ))
_sym_db.RegisterMessage(IpTraffic)



_EXPENSES = _descriptor.ServiceDescriptor(
  name='Expenses',
  full_name='Expenses',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=668,
  serialized_end=840,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetExpensesPeriods',
    full_name='Expenses.GetExpensesPeriods',
    index=0,
    containing_service=None,
    input_type=_GETEXPENSESPERIODSREQUEST,
    output_type=_GETEXPENSESPERIODSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetExpensesForPeriod',
    full_name='Expenses.GetExpensesForPeriod',
    index=1,
    containing_service=None,
    input_type=_GETEXPENSESFORPERIODREQUEST,
    output_type=_GETEXPENSESFORPERIODREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXPENSES)

DESCRIPTOR.services_by_name['Expenses'] = _EXPENSES

# @@protoc_insertion_point(module_scope)
