# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.pilling.rpc.protos.payments_pb2 as payments__pb2


class PaymentsStub(object):
  """Payments service 
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPayments = channel.unary_unary(
        '/Payments/GetPayments',
        request_serializer=payments__pb2.GetPaymentsRequest.SerializeToString,
        response_deserializer=payments__pb2.GetPaymentsReply.FromString,
        )
    self.ResolvePaymentTargetByAccount = channel.unary_unary(
        '/Payments/ResolvePaymentTargetByAccount',
        request_serializer=payments__pb2.PaymentTargetByAccountRequest.SerializeToString,
        response_deserializer=payments__pb2.PaymentTargetReply.FromString,
        )
    self.ValidatePayment = channel.unary_unary(
        '/Payments/ValidatePayment',
        request_serializer=payments__pb2.CreatePaymentRequest.SerializeToString,
        response_deserializer=payments__pb2.CreatePaymentReply.FromString,
        )
    self.CreatePayment = channel.unary_unary(
        '/Payments/CreatePayment',
        request_serializer=payments__pb2.CreatePaymentRequest.SerializeToString,
        response_deserializer=payments__pb2.CreatePaymentReply.FromString,
        )
    self.CreateOnlinePaymentOrder = channel.unary_unary(
        '/Payments/CreateOnlinePaymentOrder',
        request_serializer=payments__pb2.CreateOnlinePaymentOrderRequest.SerializeToString,
        response_deserializer=payments__pb2.CreateOnlinePaymentOrderReply.FromString,
        )
    self.OnlinePaymentOrderStatus = channel.unary_unary(
        '/Payments/OnlinePaymentOrderStatus',
        request_serializer=payments__pb2.OnlinePaymentOrderStatusRequest.SerializeToString,
        response_deserializer=payments__pb2.OnlinePaymentOrderStatusReply.FromString,
        )
    self.QRPayment = channel.unary_unary(
        '/Payments/QRPayment',
        request_serializer=payments__pb2.QRPaymentRequest.SerializeToString,
        response_deserializer=payments__pb2.QRPaymentReply.FromString,
        )


class PaymentsServicer(object):
  """Payments service 
  """

  def GetPayments(self, request, context):
    """Get payments, order by time 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResolvePaymentTargetByAccount(self, request, context):
    """-- Payment target resolver methods

    Resolve payment target by account 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidatePayment(self, request, context):
    """-- Payment creation methods

    Validate payment
    doesn't check existing payment similarity if operation id already exists.
    if both account and organization set, checks for an account
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePayment(self, request, context):
    """Create payment.
    doesn't check existing payment similarity if operation id already exists.
    if both account and organization set, checks for an account
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateOnlinePaymentOrder(self, request, context):
    """-- Order creation methods

    Create online payment order 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OnlinePaymentOrderStatus(self, request, context):
    """Check online payment order status 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QRPayment(self, request, context):
    """QR code payment 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PaymentsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPayments': grpc.unary_unary_rpc_method_handler(
          servicer.GetPayments,
          request_deserializer=payments__pb2.GetPaymentsRequest.FromString,
          response_serializer=payments__pb2.GetPaymentsReply.SerializeToString,
      ),
      'ResolvePaymentTargetByAccount': grpc.unary_unary_rpc_method_handler(
          servicer.ResolvePaymentTargetByAccount,
          request_deserializer=payments__pb2.PaymentTargetByAccountRequest.FromString,
          response_serializer=payments__pb2.PaymentTargetReply.SerializeToString,
      ),
      'ValidatePayment': grpc.unary_unary_rpc_method_handler(
          servicer.ValidatePayment,
          request_deserializer=payments__pb2.CreatePaymentRequest.FromString,
          response_serializer=payments__pb2.CreatePaymentReply.SerializeToString,
      ),
      'CreatePayment': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePayment,
          request_deserializer=payments__pb2.CreatePaymentRequest.FromString,
          response_serializer=payments__pb2.CreatePaymentReply.SerializeToString,
      ),
      'CreateOnlinePaymentOrder': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOnlinePaymentOrder,
          request_deserializer=payments__pb2.CreateOnlinePaymentOrderRequest.FromString,
          response_serializer=payments__pb2.CreateOnlinePaymentOrderReply.SerializeToString,
      ),
      'OnlinePaymentOrderStatus': grpc.unary_unary_rpc_method_handler(
          servicer.OnlinePaymentOrderStatus,
          request_deserializer=payments__pb2.OnlinePaymentOrderStatusRequest.FromString,
          response_serializer=payments__pb2.OnlinePaymentOrderStatusReply.SerializeToString,
      ),
      'QRPayment': grpc.unary_unary_rpc_method_handler(
          servicer.QRPayment,
          request_deserializer=payments__pb2.QRPaymentRequest.FromString,
          response_serializer=payments__pb2.QRPaymentReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Payments', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
